= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.5.1...v0.6.0++[0.6.0^] (2020-12-16)

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/eebb7e0ea6b09bf2e9f4b53924842933f1c94fff[eebb7e0^])
* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/keepalived-formula/commit/15e3cdb6a2318f5e9bcb47c885162079013dcaf6[15e3cdb^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/02347adaac42522fb27bb50dc0211703abfcf7e5[02347ad^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/161c6a615602ec14923e3bfaa05577de3a0adbac[161c6a6^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/6d366861bf53960cb0a6adbee14a06232aaee67e[6d36686^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/ec4fa7bc11a1bf050a127cb43b59334d70e04902[ec4fa7b^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/635902dd4d2eb0e4e003a314520eca4ab9acd75e[635902d^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/3ae2959f1305a6da1120f5c8e1cbcc7fd7422d70[3ae2959^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/80bdb6cac4f381441975df7765dab6c0cb690975[80bdb6c^])

=== Features

* *config:* add support for switch type parameters
(https://github.com/saltstack-formulas/keepalived-formula/commit/20d67c13a17377ef59df9fcd0970354d90aec772[20d67c1^])
* *scripts:* deploy helper scripts
(https://github.com/saltstack-formulas/keepalived-formula/commit/5fc37fa6fb319ef8c718b1e8e4979bce77282021[5fc37fa^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/16d674294900317db54e8133a35a5871553d4afb[16d6742^])

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.5.0...v0.5.1++[0.5.1^] (2020-04-07)

=== Bug Fixes

* *service:* restart service if config changes
(https://github.com/saltstack-formulas/keepalived-formula/commit/0490489614ef1374dadce88c734b8dadfe701f5f[0490489^]),
closes
https://github.com/saltstack-formulas/keepalived-formula/issues/37[#37^]

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.4.5...v0.5.0++[0.5.0^] (2020-04-06)

=== Bug Fixes

* *libtofs:* “files_switch” mess up the variable exported by “map.jinja”
 [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/e01cd28115d1e0c282dd6d8f68cdf8c514abbe16[e01cd28^])

=== Continuous Integration

* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/05a095954d5195d28af6c8b467ef28eb9e1b18d0[05a0959^])

=== Features

* *vrrp_sync_group:* added option for vrrp_sync_group
(https://github.com/saltstack-formulas/keepalived-formula/commit/45e3261e53b42e611d2d2ec92135bf554f6500f8[45e3261^])

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.4.4...v0.4.5++[0.4.5^] (2020-01-27)

=== Bug Fixes

* *keepalived.conf.tmpl.jinja:* fix `has no attribute` error
(https://github.com/saltstack-formulas/keepalived-formula/commit/4391459df8cabb4818e54f54b92d5ca067671956[4391459^]),
closes
https://github.com//freenode.logbot.info/saltstack-formulas/20200122/issues/c3126298-c3126299[/freenode.logbot.info/saltstack-formulas/20200122#c3126298-c3126299^]
* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/e9f7b11db30e370d37059e599f35130e1137dd0a[e9f7b11^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/a1a51d58421ed65f56703a5b011178fc5122e26f[a1a51d5^])
* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/0bb4271c89b2a64ae536e08047eb835c121dac90[0bb4271^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/2758e8ebf360be54682ee09b59a5f2767f721bbd[2758e8e^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/e6381581fad1568e7f21f34776ca46a6cd137d36[e638158^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/4f492dafff1da17a180e63181ab5c509e65cb189[4f492da^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/cc7542a93f03dc8bedb5bb7ac54c2bf17d30cd02[cc7542a^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/5e42eaaa56f45a1b4c2f60fa9087f7006c865bcc[5e42eaa^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/47b3bce96b50f5059db0c7011497ca0a0406bcf8[47b3bce^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/4d4021675480cb44e6084a5b91ec5c9963ce831f[4d40216^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/3e9bc91558ade2614f8de256092bfad8179feb4e[3e9bc91^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/2d42d932463df75931a721ab9c7f3dbe6a584767[2d42d93^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/603176eec75d8602944904e2c389d483d8d34a52[603176e^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/01df0d0097457cc28fbde9fd5a542848c37804f2[01df0d0^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/45a87c67fd28e8f78a887a0a7453dd7d7c9b43d7[45a87c6^])

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.4.3...v0.4.4++[0.4.4^] (2019-10-12)

=== Bug Fixes

* *rubocop:* add fixes using `rubocop --safe-auto-correct`
(https://github.com/saltstack-formulas/keepalived-formula/commit/ce52e09[ce52e09^])

=== Continuous Integration

* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/keepalived-formula/commit/676b623[676b623^])
* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/eaaaf9e[eaaaf9e^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci]
(https://github.com/saltstack-formulas/keepalived-formula/commit/3419a72[3419a72^])
* *kitchen+travis:* replace EOL pre-salted images
(https://github.com/saltstack-formulas/keepalived-formula/commit/2de0ca2[2de0ca2^])
* *platform:* add `arch-base-latest`
(https://github.com/saltstack-formulas/keepalived-formula/commit/39f1205[39f1205^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/keepalived-formula/commit/ff62d0b[ff62d0b^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/keepalived-formula/commit/0645ea6[0645ea6^])
* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/keepalived-formula/commit/2cb407f[2cb407f^])
* *travis:* merge `rubocop` linter into main `lint` job
(https://github.com/saltstack-formulas/keepalived-formula/commit/49892c0[49892c0^])
* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/keepalived-formula/commit/0b782d6[0b782d6^])

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.4.2...v0.4.3++[0.4.3^] (2019-08-27)

=== Code Refactoring

* *pillar:* sync map.jinja with template-formula
(https://github.com/saltstack-formulas/keepalived-formula/commit/96fe445[96fe445^])

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.4.1...v0.4.2++[0.4.2^] (2019-08-25)

=== Documentation

* *readme:* fix indentation
(https://github.com/saltstack-formulas/keepalived-formula/commit/52c1359[52c1359^])

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.4.0...v0.4.1++[0.4.1^] (2019-08-25)

=== Documentation

* *readme:* add testing section
(https://github.com/saltstack-formulas/keepalived-formula/commit/bbc0f7b[bbc0f7b^])

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.3.0...v0.4.0++[0.4.0^] (2019-08-10)

=== Continuous Integration

* *kitchen+travis:* modify matrix to include `develop` platform
(https://github.com/saltstack-formulas/keepalived-formula/commit/a9cadb3[a9cadb3^])

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/keepalived-formula/commit/9e29ffa[9e29ffa^])

== link:++https://github.com/saltstack-formulas/keepalived-formula/compare/v0.2.0...v0.3.0++[0.3.0^] (2019-05-13)

=== Features

* *semantic-release:* implement an automated changelog
(https://github.com/saltstack-formulas/keepalived-formula/commit/51f872e[51f872e^])
